# Generated by Django 2.2.28 on 2022-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.SlugField()),
                ('license_plate', models.CharField(max_length=256)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(max_length=256)),
            ],
        ),
    ]
